---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventlisteners.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - all
      - tekton-triggers
    kind: EventListener
    plural: eventlisteners
    shortNames:
      - el
    singular: eventlistener
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
