---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggertemplates.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - all
      - tekton-triggers
    kind: TriggerTemplate
    plural: triggertemplates
    shortNames:
      - tt
    singular: triggertemplate
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
