---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggerbindings.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - all
      - tekton-triggers
    kind: TriggerBinding
    plural: triggerbindings
    shortNames:
      - tb
    singular: triggerbinding
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
