---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "project-github-webhook.fullname" . }}-event-listener
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "project-github-webhook.chart" . }}
    app.kubernetes.io/name: {{ include "project-github-webhook.name" . }}-event-listener
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
spec:
  serviceAccountName: {{ include "project-github-webhook.fullname" . }}
  triggers:
    - name: on-commit
      interceptor:
        github:
          secretRef:
            secretName: {{ .Values.github.secret.name }}
            secretKey: {{ .Values.github.secret.key }}
            namespace: {{ .Values.github.secret.namespace }}
          eventTypes:
          - push
      bindings:
      - name: {{ include "project-github-webhook.fullname" . }}-trigger-binding
      template:
        name: {{ include "project-github-webhook.fullname" . }}-trigger-template
