---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "project-github-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "project-github-webhook.chart" . }}
    app.kubernetes.io/name: {{ include "project-github-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
roleRef:
  kind: Role
  name: {{ include "project-github-webhook.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "project-github-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
