---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "build-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "build-bot.chart" . }}
    app.kubernetes.io/name: {{ include "build-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
{{- with.Values.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
