---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "build-bot.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "build-bot.chart" . }}
    app.kubernetes.io/name: {{ include "build-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
roleRef:
  kind: Role
  name: {{ include "build-bot.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "build-bot.fullname" . }}
    namespace: {{ .Values.namespace }}
