apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelinerunrequests.datap.io
spec:
  group: datap.io
  names:
    kind: PipelineRunRequest
    listKind: PipelineRunRequestList
    plural: pipelinerunrequests
    singular: pipelinerunrequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            pipeline:
              type: string
            server:
              type: string
            extraResources:
              type: array
              items:
                type: object
                x-kubernetes-preserve-unknown-fields: true
          required:
            - pipeline
            - server
          x-kubernetes-preserve-unknown-fields: true
        status:
          type: object
          properties:
            scheduled:
              type: boolean
            archived:
              type: boolean
      required:
        - spec
  versions:
    - name: v1alpha1
      served: true
      storage: true
