version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sources/sdk/k8s-operator"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/sources/sdk/amqp-engine"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/sources/sdk/pacman"
    schedule:
      interval: "daily"
