version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    labels: []
    commit-message:
      prefix: ':arrow_up: '
      prefix-development: ':arrow_up: '
