apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.datap.io
spec:
  group: datap.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            manifest_path:
              type: string
            pipeline_executor:
              type: object
              properties:
                image:
                  type: object
                  properties:
                    name:
                      type: string
                    tag:
                      type: string
                  required:
                    - name
                    - tag
                required:
                  - image
            webhooks:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  max_concurrent_jobs:
                    type: integer
                    minimum: 1
                  history:
                    type: integer
                    minimum: 0
                  workspace:
                    type: object
                    properties:
                      storage_size:
                        type: string
                      storage_class:
                        type: string
                  github_secret:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                    required:
                      - name
                      - key
                required:
                  - name
                  - github_secret
        status:
          type: object
          properties:
            webhooks:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  url:
                    type: string
                required:
                  - name
                  - url
      required:
        - spec
  versions:
    - name: v1alpha1
      served: true
      storage: true
