---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tekton.fullname" . }}-triggers-controller
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "tekton.chart" . }}
    app.kubernetes.io/name: {{ include "tekton.name" . }}-triggers-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
spec:
  replicas: {{ .Values.replicas.triggers_controller }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tekton.chart" . }}-triggers-controller
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: {{ include "tekton.chart" . }}-triggers-controller
    spec:
      serviceAccountName: {{ include "tekton.fullname" . }}-triggers-controller
      containers:
        - name: tekton-triggers-controller
          image: {{.Values.image.triggers_controller.name }}:{{ .Values.image.triggers_controller.tag }}
          imagePullPolicy: {{ .Values.image.triggers_controller.pullPolicy }}
          args:
            - -logtostderr
            - -stderrthreshold
            - INFO
            - -el-image
            - {{ .Values.image.event_listener.name }}:{{ .Values.image.event_listener.tag }}
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging-triggers
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability-triggers
            - name: METRICS_DOMAIN
              value: tekton.dev/triggers
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
      volumes:
        - configMap:
            name: config-logging-triggers
          name: config-logging
