---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelineruns.tekton.dev
  labels:
    helm.sh/chart: {{ include "tekton.chart" . }}
    app.kubernetes.io/name: pipelineruns.tekton.dev
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio

spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    - JSONPath: .status.conditions[?(@.type=="Succeeded")].reason
      name: Reason
      type: string
    - JSONPath: .status.startTime
      name: StartTime
      type: date
    - JSONPath: .status.completionTime
      name: CompletionTime
      type: date
  group: tekton.dev
  names:
    categories:
      - all
      - tekton-pipelines
    kind: PipelineRun
    plural: pipelineruns
    shortNames:
      - pr
      - prs
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
