---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metacontroller.fullname" . }}
  labels:
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
subjects:
- kind: ServiceAccount
  name: {{ include "metacontroller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "metacontroller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
