---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: controllerrevisions
    singular: controllerrevision
    kind: ControllerRevision
