---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "metacontroller.fullname" . }}-aggregate-view
  labels:
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}-aggregate-view
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - metacontroller.k8s.io
  resources:
  - compositecontrollers
  - controllerrevisions
  - decoratorcontrollers
  verbs:
  - get
  - list
  - watch
