---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipelinerunserver-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "pipelinerunserver-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          # Replace this with the built image name
          image: "{{ .Values.operator.image.name }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: "{{ .Values.operator.image.pullPolicy }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ .Chart.Name }}"
            - name: ANSIBLE_GATHERING
              value: explicit
          envFrom:
            - configMapRef:
                name: {{ include "pipelinerunserver-operator.fullname" . }}
      volumes:
        - name: runner
          emptyDir: {}
