---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "tekton.fullname" . }}-pipelines
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "tekton.chart" . }}
    app.kubernetes.io/name: {{ include "tekton.name" . }}-pipelines
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  volumes:
    - emptyDir
    - configMap
    - secret
