describe('KubeInterface', require('./kube-interface'))
describe('APIService', require('./api-service'))
describe('CancelScope', require('./cancel-scope'))
describe('Operator', require('./operator'))
describe('ResourceWatcher', require('./resource-watcher'))
describe('ServerFactory', require('./server-factory'))