---

- name: create pipeline pipeline-executor
  k8s:
    definition:
      apiVersion: tekton.dev/v1alpha1
      kind: Pipeline
      metadata:
        name: pipeline-executor
        namespace: "{{ namespace }}"
      spec:
        params:
          - name: git_url
            type: string
          - name: git_revision
            type: string
          - name: workspace_pvc
            type: string
        workspaces:
          - name: repository
        tasks:
          - name: checkout-scm
            taskRef:
              name: git-clone
            workspaces:
              - name: output
                workspace: repository
            params:
              - name: url
                value: $(params.git_url)
              - name: revision
                value: $(params.git_revision)
          - name: run-pipeline-executor
            taskRef:
              name: pipeline-exec
            params:
              - name: workspace_pvc
                value: $(params.workspace_pvc)
            workspaces:
              - name: sources
                workspace: repository
