---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "project-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "project-operator.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - pipelines
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - datap.io
    resources:
      - projects
      - pipelinerunservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "project-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "project-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "project-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
