---
name: Base Build Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@scm
        uses: actions/checkout@master

      - name: notify@slack
        uses: Ilshidur/action-slack@master
        env:
          SLACK_USERNAME: CIBot
          SLACK_OVERRIDE_MESSAGE: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: "[<https://github.com/datapio/opencore|opencore>] [<https://github.com/datapio/tree/${{ github.ref }}|${{ github.ref }}>] Base Build: ${{ job.status }}"
        if: always()
