---
name: System Build Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@scm
        uses: actions/checkout@master

      - name: user-admission-webhook@docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: datapio/opencore/user-admission-webhook
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: sources/user-admission-webhook
          dockerfile: docker/Dockerfile
          cache: true

      - name: project-controller@docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: datapio/opencore/project-controller
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: sources/project-controller
          dockerfile: docker/Dockerfile
          cache: true

      - name: project-admission-webhook@docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: datapio/opencore/project-admission-webhook
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: sources/project-admission-webhook
          dockerfile: docker/Dockerfile
          cache: true

      - name: release-controller@docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: datapio/opencore/release-controller
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: sources/release-controller
          dockerfile: docker/Dockerfile
          cache: true

      - name: secret-injector@docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: datapio/opencore/secret-injector
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: sources/secret-injector
          dockerfile: docker/Dockerfile
          cache: true

      - name: notify@slack
        uses: Ilshidur/action-slack@master
        env:
          SLACK_USERNAME: CIBot
          SLACK_OVERRIDE_MESSAGE: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: "[<https://github.com/datapio/opencore|opencore>] [<https://github.com/datapio/tree/${{ github.ref }}|${{ github.ref }}>] System Build: ${{ job.status }}"
        if: always()
