---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton.fullname" . }}-pipelines-controller
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "tekton.chart" . }}
    app.kubernetes.io/name: {{ include "tekton.name" . }}-pipelines-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
